### ISSUE TITLE
Copyright / Intellectual Property

### ISSUE THREAD

**Issue by cedey23** [jacoavery/csc-major-project#1]
If you are using external sources (You Tube) for your background data / video resources, be aware of copyright / intellectual property infringement.

Video can be embedded as long as you have copyright or have recorded the video yourself. Otherwise you will need to use embedded links to an external source.

**Comment by jacoavery** [comment]
I will contact the creators of the videos I may be using and talk to them about copyright issues. Until then I will be using embedded links to an external source.
